/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package puzzlehash;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author furid
 */
public class Vista extends javax.swing.JFrame {

    SearchHash HiloSecuencial = null;
    SearchHashConcurrente HiloConcurrente = null;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        txtHash.setText(Hashing.sha256(txtMainText.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMainText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHash = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegex = new javax.swing.JTextField();
        pnlSecuencial = new javax.swing.JPanel();
        lblTitleSecu = new javax.swing.JLabel();
        btnStopSecu = new javax.swing.JButton();
        btnStartSecu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaxIntentos = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIntentosSecu = new javax.swing.JLabel();
        lblKeys = new javax.swing.JLabel();
        lblKeysSecu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHASHSecu = new javax.swing.JTextField();
        lblTimeEndSecu = new javax.swing.JLabel();
        pnlConcurrente = new javax.swing.JPanel();
        lblTitleSecu1 = new javax.swing.JLabel();
        btnStopConcu = new javax.swing.JButton();
        btnStartConcu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMaxIntentosConcu = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHASHConcu = new javax.swing.JTextField();
        lblTimeEndConcu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogConcurrente = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtMaxIntentosConcu1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        lblKeysConcu = new javax.swing.JLabel();
        lblIntentosConcu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puzzle Hash");
        setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setName("mainFrame"); // NOI18N
        setSize(new java.awt.Dimension(800, 800));

        pnlContent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlContent.setAlignmentX(0.0F);
        pnlContent.setAlignmentY(0.0F);
        pnlContent.setMaximumSize(getPreferredSize());
        pnlContent.setMinimumSize(getPreferredSize());

        pnlHeader.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlHeader.setMaximumSize(new java.awt.Dimension(788, 75));
        pnlHeader.setMinimumSize(new java.awt.Dimension(788, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ingresa Texto");

        txtMainText.setText("Hola Mundo");
        txtMainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMainTextActionPerformed(evt);
            }
        });
        txtMainText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMainTextKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("HASH Result");

        txtHash.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Exprecion a buscar (Regex)");

        txtRegex.setText("[0]{2}.*");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMainText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addComponent(txtHash)
                        .addGap(18, 18, 18)
                        .addComponent(txtRegex, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSecuencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblTitleSecu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleSecu.setText("Secuencial");

        btnStopSecu.setBackground(new java.awt.Color(102, 0, 0));
        btnStopSecu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStopSecu.setForeground(new java.awt.Color(255, 255, 255));
        btnStopSecu.setText("Parar");
        btnStopSecu.setEnabled(false);
        btnStopSecu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopSecuMouseClicked(evt);
            }
        });

        btnStartSecu.setBackground(new java.awt.Color(51, 102, 0));
        btnStartSecu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStartSecu.setForeground(new java.awt.Color(255, 255, 255));
        btnStartSecu.setText("Iniciar");
        btnStartSecu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartSecuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Max Intentos (0 Infinito)");

        txtMaxIntentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaxIntentos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtMaxIntentosStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("Resultados");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Intentos");

        lblIntentosSecu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblIntentosSecu.setForeground(new java.awt.Color(102, 102, 102));
        lblIntentosSecu.setText("0");

        lblKeys.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKeys.setText("Keys");

        lblKeysSecu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblKeysSecu.setForeground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("HASH Res");

        txtHASHSecu.setEditable(false);

        lblTimeEndSecu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTimeEndSecu.setText("Tiempo: ");

        javax.swing.GroupLayout pnlSecuencialLayout = new javax.swing.GroupLayout(pnlSecuencial);
        pnlSecuencial.setLayout(pnlSecuencialLayout);
        pnlSecuencialLayout.setHorizontalGroup(
            pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecuencialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSecuencialLayout.createSequentialGroup()
                        .addGroup(pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSecuencialLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaxIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(pnlSecuencialLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIntentosSecu, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGroup(pnlSecuencialLayout.createSequentialGroup()
                                .addComponent(lblKeys)
                                .addGap(18, 18, 18)
                                .addComponent(lblKeysSecu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(136, Short.MAX_VALUE))
                    .addGroup(pnlSecuencialLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSecuencialLayout.createSequentialGroup()
                        .addComponent(lblTitleSecu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStartSecu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStopSecu)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSecuencialLayout.createSequentialGroup()
                        .addGroup(pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTimeEndSecu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHASHSecu))
                        .addContainerGap())))
        );
        pnlSecuencialLayout.setVerticalGroup(
            pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecuencialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleSecu)
                    .addComponent(btnStopSecu)
                    .addComponent(btnStartSecu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaxIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblIntentosSecu))
                .addGap(44, 44, 44)
                .addGroup(pnlSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeys)
                    .addComponent(lblKeysSecu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHASHSecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTimeEndSecu)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlConcurrente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblTitleSecu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleSecu1.setText("Concurrente");

        btnStopConcu.setBackground(new java.awt.Color(102, 0, 0));
        btnStopConcu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStopConcu.setForeground(new java.awt.Color(255, 255, 255));
        btnStopConcu.setText("Parar");
        btnStopConcu.setEnabled(false);
        btnStopConcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopConcuMouseClicked(evt);
            }
        });

        btnStartConcu.setBackground(new java.awt.Color(51, 102, 0));
        btnStartConcu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStartConcu.setForeground(new java.awt.Color(255, 255, 255));
        btnStartConcu.setText("Iniciar");
        btnStartConcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartConcuMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Max Intentos (0 Infinito)");

        txtMaxIntentosConcu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaxIntentosConcu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtMaxIntentosConcuStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("Resultados");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("HASH Res");

        txtHASHConcu.setEditable(false);

        lblTimeEndConcu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTimeEndConcu.setText("Tiempo: ");

        txtLogConcurrente.setEditable(false);
        txtLogConcurrente.setColumns(20);
        txtLogConcurrente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLogConcurrente.setRows(5);
        jScrollPane1.setViewportView(txtLogConcurrente);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Cant Hilos");

        txtMaxIntentosConcu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaxIntentosConcu1.setValue(1);
        txtMaxIntentosConcu1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtMaxIntentosConcu1StateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Keys");

        lblKeysConcu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblKeysConcu.setForeground(new java.awt.Color(102, 102, 102));

        lblIntentosConcu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblIntentosConcu.setForeground(new java.awt.Color(102, 102, 102));
        lblIntentosConcu.setText("0");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Intentos");

        javax.swing.GroupLayout pnlConcurrenteLayout = new javax.swing.GroupLayout(pnlConcurrente);
        pnlConcurrente.setLayout(pnlConcurrenteLayout);
        pnlConcurrenteLayout.setHorizontalGroup(
            pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConcurrenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConcurrenteLayout.createSequentialGroup()
                        .addComponent(lblTitleSecu1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addComponent(btnStartConcu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStopConcu))
                    .addComponent(txtHASHConcu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTimeEndConcu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlConcurrenteLayout.createSequentialGroup()
                        .addGroup(pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConcurrenteLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaxIntentosConcu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addGroup(pnlConcurrenteLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaxIntentosConcu1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlConcurrenteLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKeysConcu, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(lblIntentosConcu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlConcurrenteLayout.setVerticalGroup(
            pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConcurrenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleSecu1)
                    .addComponent(btnStopConcu)
                    .addComponent(btnStartConcu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaxIntentosConcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaxIntentosConcu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lblKeysConcu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(lblIntentosConcu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHASHConcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimeEndConcu)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(pnlSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlConcurrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConcurrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartConcuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartConcuMouseClicked
        // TODO add your handling code here:
        if (ValidForm()) {
            txtLogConcurrente.setText("");
            txtHASHConcu.setText("");
            lblKeysConcu.setText("");
            lblTimeEndConcu.setText("");
            lblIntentosConcu.setText("");
            SetStartConcurrent(true);
            HiloConcurrente = new SearchHashConcurrente(txtMainText.getText(),
                    txtRegex.getText(),
                    (int) txtMaxIntentosConcu.getValue(),
                    "Hilo Secuencial",
                    (int) txtMaxIntentosConcu1.getValue(),
                    txtLogConcurrente,
                    btnStopConcu,
                    lblIntentosConcu
            );
            HiloConcurrente.start();
        }
    }//GEN-LAST:event_btnStartConcuMouseClicked

    private void btnStopConcuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopConcuMouseClicked
        // TODO add your handling code here:
        if (HiloConcurrente != null) {
            try {
                HiloConcurrente.flagTread = false;
                lblKeysConcu.setText(String.valueOf(HiloConcurrente.key));
                txtHASHConcu.setText(HiloConcurrente.HashFinding);
                lblTimeEndConcu.setText(HiloConcurrente.TimerEnd);
                SetStartConcurrent(false);
            } catch (Throwable ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            SetStartConcurrent(false);
        }
    }//GEN-LAST:event_btnStopConcuMouseClicked

    private void txtMaxIntentosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtMaxIntentosStateChanged
        // TODO add your handling code here:
        if ((int) txtMaxIntentos.getValue() < 0)
            txtMaxIntentos.setValue(0);
    }//GEN-LAST:event_txtMaxIntentosStateChanged

    private void btnStartSecuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartSecuMouseClicked
        // TODO add your handling code here:
        if (ValidForm()) {
            lblIntentosSecu.setText("0");
            SetStartSecuencial(true);
            HiloSecuencial = new SearchHash(txtMainText.getText(),
                    txtRegex.getText(),
                    (int) txtMaxIntentos.getValue(),
                    "Hilo Secuencial",
                    lblIntentosSecu,
                    btnStopSecu
            );
            HiloSecuencial.start();

        }
    }//GEN-LAST:event_btnStartSecuMouseClicked

    private void btnStopSecuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopSecuMouseClicked
        // TODO add your handling code here:
        if (HiloSecuencial != null) {
            try {
                HiloSecuencial.flagTread = false;
                lblKeysSecu.setText(String.valueOf(HiloSecuencial.key));
                txtHASHSecu.setText(HiloSecuencial.HashFinding);
                lblTimeEndSecu.setText(HiloSecuencial.TimerEnd);
                SetStartSecuencial(false);
            } catch (Throwable ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            SetStartSecuencial(false);
        }
    }//GEN-LAST:event_btnStopSecuMouseClicked

    private void txtMainTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMainTextKeyTyped
        // TODO add your handling code here:
        if (txtMainText.getText().isEmpty())
            txtHash.setText("");
        else
            txtHash.setText(Hashing.sha256(txtMainText.getText()));
    }//GEN-LAST:event_txtMainTextKeyTyped

    private void txtMainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMainTextActionPerformed

    private void txtMaxIntentosConcu1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtMaxIntentosConcu1StateChanged
        // TODO add your handling code here:
        if ((int) txtMaxIntentosConcu1.getValue() < 1)
            txtMaxIntentosConcu1.setValue(1);
    }//GEN-LAST:event_txtMaxIntentosConcu1StateChanged

    private void txtMaxIntentosConcuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtMaxIntentosConcuStateChanged
        // TODO add your handling code here:
        if ((int) txtMaxIntentosConcu.getValue() < 0)
            txtMaxIntentosConcu.setValue(0);
    }//GEN-LAST:event_txtMaxIntentosConcuStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartConcu;
    private javax.swing.JButton btnStartSecu;
    private javax.swing.JButton btnStopConcu;
    private javax.swing.JButton btnStopSecu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntentosConcu;
    private javax.swing.JLabel lblIntentosSecu;
    private javax.swing.JLabel lblKeys;
    private javax.swing.JLabel lblKeysConcu;
    private javax.swing.JLabel lblKeysSecu;
    private javax.swing.JLabel lblTimeEndConcu;
    private javax.swing.JLabel lblTimeEndSecu;
    private javax.swing.JLabel lblTitleSecu;
    private javax.swing.JLabel lblTitleSecu1;
    private javax.swing.JPanel pnlConcurrente;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlSecuencial;
    private javax.swing.JTextField txtHASHConcu;
    private javax.swing.JTextField txtHASHSecu;
    private javax.swing.JTextField txtHash;
    private javax.swing.JTextArea txtLogConcurrente;
    private javax.swing.JTextField txtMainText;
    private javax.swing.JSpinner txtMaxIntentos;
    private javax.swing.JSpinner txtMaxIntentosConcu;
    private javax.swing.JSpinner txtMaxIntentosConcu1;
    private javax.swing.JTextField txtRegex;
    // End of variables declaration//GEN-END:variables

    private boolean ValidForm() {
        if (txtMainText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(pnlContent, "Favor de ingresar un texto incicial!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtRegex.getText().isEmpty()) {
            JOptionPane.showMessageDialog(pnlContent, "Favor de ingresar un texto o exprecion a buscar!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    private void SetStartSecuencial(boolean b) {
        btnStartSecu.setEnabled(!b);
        btnStopSecu.setEnabled(b);
        txtMaxIntentos.setEnabled(!b);
        txtMainText.setEnabled(!b);
        txtRegex.setEnabled(!b);
    }

    private void SetStartConcurrent(boolean b) {
        btnStartConcu.setEnabled(!b);
        btnStopConcu.setEnabled(b);
        txtMainText.setEnabled(!b);
        txtRegex.setEnabled(!b);
    }
}
